version: '3.2'

services:
  auth:
    container_name: umag-auth-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8224:8080
    networks:
      - umag_network
    env_file:
      - ./.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auth_backend.entrypoints=web,websecure"
      - "traefik.http.services.auth_backend.loadbalancer.server.port=8224"
      - "traefik.http.routers.auth_backend.service=auth_backend"
      - "traefik.http.routers.auth_backend.rule=Host(`sid.pichimalen.org`) && (PathPrefix(`/api/v1/auth/user`) || PathPrefix(`/api/v1/auth/login`) || PathPrefix(`/api/v1/auth/refresh`))"      
      - "traefik.http.routers.auth_backend.tls=true"
networks:
  umag_network:
    name: umag_network
